import { Link } from 'react-router'

export function Methodology() {
  return <article className="methodology"><div className="page-heading"><p className="eyebrow">Entender antes de interpretar</p><h1>Como olhamos para as cores.</h1><p>Os números ajudam a encontrar pontos de revisão. A avaliação completa de acessibilidade continua dependendo de testes e revisão humana.</p></div>
    <section><h2>1. Coleta da página</h2><p>O back-end abre a URL pública no Chromium, em uma janela de 1280 × 720 pixels, e coleta textos, cores computadas, tamanho, peso e posição. A captura inclui a página inteira, dentro dos limites de altura (12.000 px) e coleta (2.000 blocos de texto).</p><p>Há espera de 500 ms após o carregamento e timeout de 15 s por operação. Conteúdo tardio, frames e partes ocultas ou sobrepostas podem não ser representados. Endereços privados e redirecionamentos são bloqueados; use a URL final.</p></section>
    <section><h2>2. Contraste e score</h2><p>Calculamos a luminância relativa sRGB e a razão de contraste entre texto e fundo. O critério AA é 4,5:1 para texto comum e 3:1 para texto grande: pelo menos 24 px, ou 18,67 px com peso 700 ou maior.</p><p className="formula">score = arredondar(100 × textos aprovados em AA / textos avaliáveis)</p><p>Sem textos avaliáveis, o score fica indisponível. Textos não avaliáveis e avisos de diferenciação não entram na fórmula. O score é próprio do KidoColors e não é uma nota oficial WCAG.</p><p>Gradientes, imagens de fundo, efeitos, filtros e composições que o coletor não resolve confiavelmente são sinalizados como não avaliáveis. A sugestão altera apenas a cor do texto, aproximando-a de preto ou branco até atingir o contraste mínimo, mantendo o fundo.</p></section>
    <section><h2>3. Simulações de cores</h2><p>Aplicamos as matrizes de Machado, Oliveira e Fernandes (2009), na intensidade máxima, ao RGB linear, com conversão de volta para sRGB. As imagens de protanopia e deuteranopia são simulações; a imagem chamada tritanopia usa a aproximação máxima de tritanomalia do modelo.</p><p>Essas imagens não representam exatamente a visão de uma pessoa. A aproximação para tritanopia não deve ser interpretada como reprodução fisiológica validada.</p></section>
    <section><h2>4. Avisos de diferenciação</h2><p>Comparamos cores de texto e cores de fundo de blocos próximos (até 200 px de separação), com limite de 20.000 pares. O aviso ocorre quando a distância RGB normalizada original é pelo menos 0,20 e a distância simulada cai para no máximo 0,08 e 40% da original.</p><p>Essa distância é euclidiana no RGB codificado, não Delta E. Os limiares são heurísticos, sem validação perceptual ou equivalência a um critério WCAG. Pares de cores repetidos são deduplicados; os avisos exigem interpretação no contexto da página.</p></section>
    <section><h2>5. Interpretar com cuidado</h2><p>Uma captura pode mudar por rede, anúncios, consentimento, fontes, recursos bloqueados ou conteúdo dinâmico. O relatório informa textos ignorados e limites atingidos. “Nenhuma ocorrência” significa apenas que o motor não encontrou ocorrências na parte avaliada.</p><p>A ferramenta não verifica navegação por teclado, leitores de tela, semântica HTML ou todos os critérios de acessibilidade. Resultados de teste são fixtures, separados de qualquer estudo com websites reais.</p></section>
    <section><h2>6. Estudo com websites reais</h2><p>O estudo ainda não foi executado. Antes da coleta, uma amostra menor deve ser rotulada manualmente para validar o detector. Precision, recall e F1 só podem ser calculados com rótulos reais e uma unidade de avaliação compatível; a heurística de diferenciação requer validação separada.</p><p>A amostra de aproximadamente 100 URLs, suas categorias e exclusões serão definidas e aprovadas antes da execução. O processamento usará o mesmo motor da análise individual. Serão registrados dataset, versões, ambiente, data, duração e falhas. As estatísticas de score considerarão análises com avaliação válida, e as falhas serão apresentadas separadamente.</p></section>
    <section><h2>Referências</h2><ul><li><a href="https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html">WCAG 2.2: contraste mínimo</a></li><li><a href="https://www.inf.ufrgs.br/~oliveira/pubs_files/CVD_Simulation/CVD_Simulation.html">Modelo de simulação de Machado, Oliveira e Fernandes</a></li></ul></section>
    <Link className="button primary" to="/">Experimentar uma análise ↗</Link>
  </article>
}
